# I am a comment, and I want to say that the variable CC will be
# the compiler to use.
CC=g++
# Hey!, I am comment number 2. I want to say that CFLAGS will be the
# options I'll pass to the compiler.
#LIBS=-I$(CPT_PATH) -L$(CPT_PATH) -lcpt


all: day3

day3: day3.cpp
	$(CC) $^ -o day3

#bvp_example: bvp_example.cpp
#	$(CC) $^  $(LIBS) -o bvp_example

clean:
	rm -rf *o day3
